### ISSUE TITLE
Serialization error

### ISSUE THREAD

**Issue by 1719pankaj** [google-gemini/generative-ai-android#230]
### Description of the bug:

Whenever I try to ask coding questions ("write fizzbuzz in python", "implement fizzbuzz in java") it gives the below error and crashes.
Any other question asked works fine.

### Actual vs expected behavior:

model: gemini-2.0-flash-exp
sdk version: 0.9

### Any other information you'd like to share?

FATAL EXCEPTION: DefaultDispatcher-worker-3 (Ask Gemini)
                                                                                                    Process: com.example.cpplearner, PID: 11563
                                                                                                    com.google.ai.client.generativeai.type.SerializationException: Something went wrong while trying to deserialize a response from the server.
                                                                                                    	at com.google.ai.client.generativeai.type.GoogleGenerativeAIException$Companion.from(Exceptions.kt:41)
                                                                                                    	at com.google.ai.client.generativeai.GenerativeModel.generateContent(GenerativeModel.kt:108)
                                                                                                    	at com.google.ai.client.generativeai.GenerativeModel$generateContent$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e13d580, Dispatchers.IO]
                                                                                                    Caused by: io.ktor.serialization.JsonConvertException: Illegal input: Field 'uri' is required for type with serial name 'com.google.ai.client.generativeai.common.server.CitationSources', but it was missing at path: $.candidates[0].citationMetadata.citationSources[1]
                                                                                                    	at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:90)
                                                                                                    	at io.ktor.serialization.ContentConverterKt$deserialize$$inlined$map$1$2.emit(Emitters.kt:224)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:116)
                                                                                                    	at io.ktor.serialization.ContentConverterKt$deserialize$$inlined$map$1.collect(SafeCollector.common.kt:113)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ReduceKt.firstOrNull(Reduce.kt:243)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt.firstOrNull(Unknown Source:1)
                                                                                                    	at io.ktor.serialization.ContentConverterKt.deserialize(ContentConverter.kt:123)
                                                                                                    	at io.ktor.client.plugins.contentnegotiation.ContentNegotiation.convertResponse$ktor_client_content_negotiation(ContentNegotiation.kt:230)
                                                                                                    	at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invokeSuspend(ContentNegotiation.kt:262)
                                                                                                    	at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invoke(Unknown Source:13)
                                                                                                    	at io.ktor.client.plugins.contentnegotiation.ContentNegotiation$Plugin$install$2.invoke(Unknown Source:6)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
                                                                                                    	at io.ktor.client.HttpClient$4.invokeSuspend(HttpClient.kt:177)
                                                                                                    	at io.ktor.client.HttpClient$4.invoke(Unknown Source:11)
                                                                                                    	at io.ktor.client.HttpClient$4.invoke(Unknown Source:6)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:88)
                                                                                                    	at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invokeSuspend(HttpCallValidator.kt:142)
                                                                                                    	at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invoke(Unknown Source:13)
                                                                                                    	at io.ktor.client.plugins.HttpCallValidator$Companion$install$2.invoke(Unknown Source:6)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
                                                                                                    	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
                                                                                                    	at io.ktor.client.call.HttpClientCall.bodyNullable(HttpClientCall.kt:88)
2024-12-31 01:23:10.871 11563-11624 AndroidRuntime          com.example.cpplearner               E  	at com.google.ai.client.generativeai.common.APIController.generateContent(APIController.kt:261) (Ask Gemini)
                                                                                                    	at com.google.ai.client.generativeai.common.APIController$generateContent$1.invokeSuspend(Unknown Source:15)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	... 6 more
                                                                                                    Caused by: kotlinx.serialization.MissingFieldException: Field 'uri' is required for type with serial name 'com.google.ai.client.generativeai.common.server.CitationSources', but it was missing at path: $.candidates[0].citationMetadata.citationSources[1]
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:95)
                                                                                                    	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
                                                                                                    	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
                                                                                                    	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:538)
                                                                                                    	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
                                                                                                    	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
                                                                                                    	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
                                                                                                    	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
                                                                                                    	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
                                                                                                    	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
                                                                                                    	at com.google.ai.client.generativeai.common.server.CitationMetadata$$serializer.deserialize(Types.kt:60)
                                                                                                    	at com.google.ai.client.generativeai.common.server.CitationMetadata$$serializer.deserialize(Types.kt:60)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
                                                                                                    	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
                                                                                                    	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:78)
                                                                                                    	at com.google.ai.client.generativeai.common.server.Candidate$$serializer.deserialize(Types.kt:51)
                                                                                                    	at com.google.ai.client.generativeai.common.server.Candidate$$serializer.deserialize(Types.kt:51)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
                                                                                                    	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
                                                                                                    	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
                                                                                                    	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:538)
                                                                                                    	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
                                                                                                    	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
                                                                                                    	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
                                                                                                    	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
                                                                                                    	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
2024-12-31 01:23:10.872 11563-11624 AndroidRuntime          com.example.cpplearner               E  	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:78) (Ask Gemini)
                                                                                                    	at com.google.ai.client.generativeai.common.GenerateContentResponse$$serializer.deserialize(Response.kt:26)
                                                                                                    	at com.google.ai.client.generativeai.common.GenerateContentResponse$$serializer.deserialize(Response.kt:26)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
                                                                                                    	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
                                                                                                    	at io.ktor.serialization.kotlinx.KotlinxSerializationConverter.deserialize(KotlinxSerializationConverter.kt:82)
                                                                                                    	... 36 more
                                                                                                    Caused by: kotlinx.serialization.MissingFieldException: Field 'uri' is required for type with serial name 'com.google.ai.client.generativeai.common.server.CitationSources', but it was missing
                                                                                                    	at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
                                                                                                    	at com.google.ai.client.generativeai.common.server.CitationSources.<init>(Types.kt:65)
                                                                                                    	at com.google.ai.client.generativeai.common.server.CitationSources$$serializer.deserialize(Types.kt:65)
                                                                                                    	at com.google.ai.client.generativeai.common.server.CitationSources$$serializer.deserialize(Types.kt:65)
                                                                                                    	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
                                                                                                    	... 72 more

**Comment by 1719pankaj** [comment]
That's not ideal but ok.
